<a href="https://colab.research.google.com/github/iras-mpark/MLA1020/blob/main/lec1-2/tensor_example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Tensor >= Rank 3 Tensor (3D Tensor)

In [2]:
x = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])
s = x.shape

In [3]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
s

(2, 2, 3)

# Tensor Slices 추출

In [5]:
y=x[1]
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
y=x[1][0]
y

array([7, 8, 9])

In [7]:
y=x[1][0][2]
y

np.int64(9)

# Structured Tensors

In [8]:
# Create a 2x3 array of zeros
x = np.zeros((2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Create a 2x3 array of ones
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Create a 2x3 array filled with random numbers from a normal distribution
x = np.random.randn(2, 3)
x

array([[ 2.36554479,  0.58460726,  2.06280905],
       [ 0.98946832,  0.92145685, -0.09221785]])

In [12]:
# Create a 3x3 identity matrix
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Create a matrix where the diagonal is a vector
x = np.diag([1, 2, 3])
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
import os

# Or you can read / write them from disk
os.makedirs('./var/', exist_ok=True)
np.save('./var/x.npy', x)
new_x = np.load('./var/x.npy')
new_x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# General Tensor form in AI

In [23]:
# A D-dimensional data point
D = 2  # Number of dimensions
x = np.ones(D)
x

array([1., 1.])

In [24]:
N = 3  # Number of examples
# A dataset of N examples, each D-dimensional point
x = np.ones((N, D))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
L = 4  # Length of sequence
# A dataset of N examples, each length L, each position is D-dimensional
x = np.ones((N, L, D))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
H = 2  # A height
W = 2  # A width
C = 3  # A number of channels (red, green, blue)
x = np.ones((N, H, W, C))
x

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])