<a href="https://colab.research.google.com/github/iras-mpark/MLA1020/blob/main/lec1-2/tensor_example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

# Tensor >= Rank 3 Tensor (3D Tensor)

In [40]:
x = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])
s = x.shape

In [41]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
s

(2, 2, 3)

# Tensor Slices 추출

In [45]:
y=x[1]
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [47]:
y=x[1][0]
y

array([7, 8, 9])

In [49]:
y=x[1][0][2]
y

np.int64(9)